import 'package:handyman_user/models/booking_card_model.dart';
import 'package:handyman_user/models/categogy_card_model.dart';

class AppLists {
  static List<String> bookingStatusList = [
    "All",
    "Pending",
    "On Going",
    "Completed"
  ];

  static List<BookingCardModel> bookingCardList = [
    BookingCardModel.fromJson({
      "image": "image1.jpg",
      "serviceName": "Floor cleaning",
      "status": "pending",
      "bookingId": 123,
      "date": "23 Jun 24",
      "time": "13:00",
      "providerName": "Apruv",
      "paymentMode": "cash",
      "price": 120.0,
      "discount": 5.0,
    }),
    BookingCardModel.fromJson({
      "image": "image2.jpg",
      "serviceName": "Carpet cleaning",
      "status": "completed",
      "bookingId": 124,
      "date": "24 Jun 24",
      "time": "14:00",
      "providerName": "Bryan",
      "paymentMode": "credit card",
      "price": 200.0,
      "discount": 10.0,
    }),
    BookingCardModel.fromJson({
      "image": "image3.jpg",
      "serviceName": "Window cleaning",
      "status": "ongoing",
      "bookingId": 125,
      "date": "25 Jun 24",
      "time": "15:00",
      "providerName": "Chris",
      "paymentMode": "paypal",
      "price": 150.0,
      "discount": 0.0,
    }),
    BookingCardModel.fromJson({
      "image": "image4.jpg",
      "serviceName": "Gardening",
      "status": "pending",
      "bookingId": 126,
      "date": "26 Jun 24",
      "time": "16:00",
      "providerName": "David",
      "paymentMode": "cash",
      "price": 180.0,
      "discount": 5.0,
    }),
    BookingCardModel.fromJson({
      "image": "image5.jpg",
      "serviceName": "Pool cleaning",
      "status": "completed",
      "bookingId": 127,
      "date": "27 Jun 24",
      "time": "17:00",
      "providerName": "Ethan",
      "paymentMode": "credit card",
      "price": 250.0,
      "discount": 15.0,
    }),
    BookingCardModel.fromJson({
      "image": "image6.jpg",
      "serviceName": "House cleaning",
      "status": "ongoing",
      "bookingId": 128,
      "date": "28 Jun 24",
      "time": "18:00",
      "providerName": "Frank",
      "paymentMode": "paypal",
      "price": 300.0,
      "discount": 20.0,
    }),
    BookingCardModel.fromJson({
      "image": "image7.jpg",
      "serviceName": "Laundry service",
      "status": "pending",
      "bookingId": 129,
      "date": "29 Jun 24",
      "time": "19:00",
      "providerName": "George",
      "paymentMode": "cash",
      "price": 80.0,
      "discount": 10.0,
    }),
    BookingCardModel.fromJson({
      "image": "image8.jpg",
      "serviceName": "Car wash",
      "status": "completed",
      "bookingId": 130,
      "date": "30 Jun 24",
      "time": "20:00",
      "providerName": "Hank",
      "paymentMode": "credit card",
      "price": 60.0,
      "discount": 5.0,
    }),
    BookingCardModel.fromJson({
      "image": "image9.jpg",
      "serviceName": "Pest control",
      "status": "ongoing",
      "bookingId": 131,
      "date": "01 Jul 24",
      "time": "21:00",
      "providerName": "Ian",
      "paymentMode": "paypal",
      "price": 100.0,
      "discount": 0.0,
    }),
    BookingCardModel.fromJson({
      "image": "image10.jpg",
      "serviceName": "Roof cleaning",
      "status": "pending",
      "bookingId": 132,
      "date": "02 Jul 24",
      "time": "22:00",
      "providerName": "Jack",
      "paymentMode": "cash",
      "price": 220.0,
      "discount": 10.0,
    }),
    BookingCardModel.fromJson({
      "image": "image11.jpg",
      "serviceName": "Appliance repair",
      "status": "completed",
      "bookingId": 133,
      "date": "03 Jul 24",
      "time": "23:00",
      "providerName": "Ken",
      "paymentMode": "credit card",
      "price": 140.0,
      "discount": 5.0,
    }),
    BookingCardModel.fromJson({
      "image": "image12.jpg",
      "serviceName": "Furniture assembly",
      "status": "ongoing",
      "bookingId": 134,
      "date": "04 Jul 24",
      "time": "10:00",
      "providerName": "Leo",
      "paymentMode": "paypal",
      "price": 170.0,
      "discount": 0.0,
    }),
    BookingCardModel.fromJson({
      "image": "image13.jpg",
      "serviceName": "Electrical repair",
      "status": "pending",
      "bookingId": 135,
      "date": "05 Jul 24",
      "time": "11:00",
      "providerName": "Mike",
      "paymentMode": "cash",
      "price": 190.0,
      "discount": 10.0,
    }),
    BookingCardModel.fromJson({
      "image": "image14.jpg",
      "serviceName": "Plumbing",
      "status": "completed",
      "bookingId": 136,
      "date": "06 Jul 24",
      "time": "12:00",
      "providerName": "Nate",
      "paymentMode": "credit card",
      "price": 160.0,
      "discount": 5.0,
    }),
    BookingCardModel.fromJson({
      "image": "image15.jpg",
      "serviceName": "Moving service",
      "status": "ongoing",
      "bookingId": 137,
      "date": "07 Jul 24",
      "time": "13:00",
      "providerName": "Oscar",
      "paymentMode": "paypal",
      "price": 280.0,
      "discount": 0.0,
    }),
    BookingCardModel.fromJson({
      "image": "image16.jpg",
      "serviceName": "Pet grooming",
      "status": "pending",
      "bookingId": 138,
      "date": "08 Jul 24",
      "time": "14:00",
      "providerName": "Paul",
      "paymentMode": "cash",
      "price": 50.0,
      "discount": 5.0,
    }),
    BookingCardModel.fromJson({
      "image": "image17.jpg",
      "serviceName": "Snow removal",
      "status": "completed",
      "bookingId": 139,
      "date": "09 Jul 24",
      "time": "15:00",
      "providerName": "Quinn",
      "paymentMode": "credit card",
      "price": 130.0,
      "discount": 10.0,
    }),
    BookingCardModel.fromJson({
      "image": "image18.jpg",
      "serviceName": "Lawn mowing",
      "status": "ongoing",
      "bookingId": 140,
      "date": "10 Jul 24",
      "time": "16:00",
      "providerName": "Ray",
      "paymentMode": "paypal",
      "price": 70.0,
      "discount": 0.0,
    }),
    BookingCardModel.fromJson({
      "image": "image19.jpg",
      "serviceName": "HVAC service",
      "status": "pending",
      "bookingId": 141,
      "date": "11 Jul 24",
      "time": "17:00",
      "providerName": "Sam",
      "paymentMode": "cash",
      "price": 240.0,
      "discount": 15.0,
    }),
    BookingCardModel.fromJson({
      "image": "image20.jpg",
      "serviceName": "Trash removal",
      "status": "completed",
      "bookingId": 142,
      "date": "12 Jul 24",
      "time": "18:00",
      "providerName": "Tom",
      "paymentMode": "credit card",
      "price": 110.0,
      "discount": 5.0,
    }),
  ];

  static List<String> category = [
    "All",
    "Wall Painting",
    "Home Painting",
  ];
  static List<CategogyCardModel> categoryCardList = [
    CategogyCardModel.fromJson({
      "image": "image.jpg",
      "category": "tv",
      "price": 100,
      "rating": 4.8,
      "serviceName": "Fixing Tv",
      "provider": "Wade Warren",
    }),
    CategogyCardModel.fromJson({
      "image": "image.jpg",
      "category": "wallPainting",
      "price": 50,
      "rating": 4.4,
      "serviceName": "wall Painting",
      "provider": "Wade Warren",
    }),
    CategogyCardModel.fromJson({
      "image": "image.jpg",
      "category": "homePainting",
      "price": 70,
      "rating": 4,
      "serviceName": "Painting Beautiful homes",
      "provider": "Wade Warren",
    }),
  ];
}
